### ISSUE TITLE
New installation message

### ISSUE THREAD

**Issue by kochen** [anahitasocial/anahita#155]
Hey,
following the `Getting Started` I installed Anahita:
> After the command is executed you can go to the http://localhost/myproject/www folder to access your Anahita installation. The first account that is created on this installation will be the Super Administrator account. Go to the http://localhost/myproject/www/people/signup and create an account.

but the installer message says:
> The first person who registers for an account becomes the Super Administrator. Point your browser to http://yoursite/people/signup and create a new account.

it'd be nice to have a more accurate/insightful message, so people get less confused.

**Comment by jerri123** [comment]
Amigao,sempre tive grande vontade de fazer uma rede social pra mim mais nao sei quais sao os procedimentos,voce poderia me orientar quanto a isso?

**Comment by rmdstudio** [comment]
@jerri123 I wish I could read and write Portuguese. If you can communicate in English join the Anahita tribe and you can get started by posting your questions on the Tribe Support group http://www.GetAnahita.com/join
