### ISSUE TITLE
[Bug] Anahita doesn't show the packages for the actors if the option "Always" is selected

### ISSUE THREAD

**Issue by lucascbeyeler** [anahitasocial/anahita#355]
Good Afternoon,

I'm having issues while homologating Anahita version 4.2.1 Birth Release. After I install any package, they are "Activate" by default, but if you try to use they doesn't show on the actors groups and users. If you go to home, the options are there, but they disapear if you go to any other page.
If you change to "Optional" they start to work correctly.

Someone can help me?

**Comment by rmdstudio** [comment]
@lucascbeyeler sorry for missing your post. You'll get answers much quicker if you post on our tribe support group https://www.getanahita.com/groups/107732-tribe-support

You can join here: https://www.getanahita.com/join

cheers
