### ISSUE TITLE
Suggested vhost config?

### ISSUE THREAD

**Issue by sigmap** [anahitasocial/anahita#493]
I'm getting a error 403 on the latest stable

Is there a suggested vhost setup or is there a way to set it up as `localhost/anahita` ?

current vhost entry```
<VirtualHost *:80>
       ServerAlias anahita.localhost
       DocumentRoot "C:/xampp/subdomains/anahita/www/"
</VirtualHost>```
Currently gives me a 403 response

error log entry
```
 [authz_core:error] [pid 2112:tid 1620] [client 127.0.0.1:12374] AH01630: client denied by server configuration: C:/xampp/subdomains/anahita/www/favicon.ico
```

**Comment by rmdstudio** [comment]
@sigmap please post support related issues in our Tribe Support group https://www.getanahita.com/groups/107732-tribe-support

**Comment by sigmap** [comment]
@rmdstudio I would need to be able to register for an account there. So I can't post there.

**Comment by sigmap** [comment]
I applied with a request and was rejected citing my issues would be solved in a future release. Forgive my skepticism. I have concerns.
![](https://i.imgur.com/y2wcXNJ.jpg "For a problem that could be solved programatically the solution that in place paints an ironic contrast fitting to your social media postings")
