### ISSUE TITLE
Add three new field in registration form

### ISSUE THREAD

**Issue by vginfotech** [anahitasocial/anahita#509]
Hello
I'm trying to add new field in registration form but i can't able to do because of every time database taken null field  i tried to check all file and query inside abstract.php file but i can't fix it also email activation link mail no working i tried through SMTP and mail function both but still not working when i install anahita www directory crated and i'm working inside it. 
please help to to fix
thanks

**Comment by rmdstudio** [comment]
@vginfotech if you start a topic on the Tribe Support group we can help you https://www.getanahita.com/groups/107732-tribe-support I got your email and sent you an invite.
