### ISSUE TITLE
PHP 7.4 Update

### ISSUE THREAD

**Issue by rmdstudio** [anahitasocial/anahita#522]
Update codebase for the new PHP 7.4 codebase following this guideline: https://github.com/php/php-src/blob/PHP-7.4/UPGRADING

**Comment by NicholasJohn16** [comment]
@rmdstudio I think it's 7.4 😛

**Comment by rmdstudio** [comment]
@NicholasJohn16 it's true, and thank you!

**Comment by rmdstudio** [comment]
Going to try this again with a new branch of the new codebase.
